# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: run build
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          TOKEN: ${{ secrets.TOKEN }}
          DATASHEET_ID: ${{ secrets.DATASHEET_ID }}
          FOLDER_ID: ${{ secrets.FOLDER_ID }}
          SPACE_ID: ${{ secrets.SPACE_ID }}
          VIEW_ID: ${{ secrets.VIEW_ID }}
        run: |
          yarn
          yarn test
          yarn build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: |
          yarn
          yarn publish --access public --tag beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN }}
